# Generated by Django 3.1.7 on 2021-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210320_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
