# Generated by Django 3.1.7 on 2021-03-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_topic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
