# Generated by Django 3.1.7 on 2021-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210320_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
