# Generated by Django 3.1.7 on 2021-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210312_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item_type',
            field=models.CharField(choices=[('task', 'Task'), ('file', 'File'), ('folder', 'Folder')], default='task', max_length=10),
        ),
    ]
