# Generated by Django 3.1.7 on 2021-03-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210316_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
