# Generated by Django 3.1.7 on 2021-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_entry_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
