# Generated by Django 3.1.7 on 2021-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210323_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='thumb_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
