# Generated by Django 3.1.7 on 2021-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210325_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='thumb_url',
            field=models.TextField(blank=True),
        ),
    ]
