# Generated by Django 3.1.7 on 2021-03-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_entry_bin_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='bin_img',
        ),
        migrations.AddField(
            model_name='entry',
            name='image_data',
            field=models.TextField(blank=True),
        ),
    ]
